name: Node.js CI test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x,19.x]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: paniervert        
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: backend_user
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install jest -g --save
      - run: npm install nodemon -g --save
      - run: psql -f initdb.sql postgresql://backend_user:12345@localhost:5432/paniervert
      - run: (npm run build&)
      - run: npm test