name: Node.js CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: paniervert        
          POSTGRES_PASSWORD: 12345
          POSTGRES_USER: backend_user
        ports:
          - 5433:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm install nodemon -g --save
      - run: (npm run dev&)
      - run: npm test
      - name: Run init script
        run: |
          sudo -u postgres psql -U backend_user -d paniervert -a -f initdb.sql