name: Node.js CI test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build --if-present
        
      - name: Install nodemon
        run: npm install nodemon -g --save
        
      - name: Start Node.js app
        run: npm run dev &

      # Add steps to set up PostgreSQL and initialize the database
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql
          sudo service postgresql start
          
      - name: Create database and run init script
        run: |
          psql -U postgres -c "CREATE DATABASE paniervert;"
          psql -U postgres -d paniervert -a -f initdb.sql
          
      - name: Run tests
        run: npm test
